env:
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'import/extensions': 0,
    'no-console': 'off',
    'no-underscore-dangle': ['error', { 'allow': ['__filename', '__dirname'] }],
  }
